### ISSUE TITLE
Synchronization of pinned memory passed in as data

### ISSUE THREAD

**Issue by pjaaskel** [CHIP-SPV/hipstar#211]
This is to check/test: If we have memory that is allocated with cuHostMemAlloc() or made pinned with cuMemHostRegister() and those pointers are passed in the kernels as data (e.g. array or struct elements), do we synchronize the modifications correctly? I recall seeing code that only checks the immediate kernel arguments and synchronizes those, but doesn't check pointers in the passed data.

**Comment by linehill** [comment]
Made a test that fails because CHIP-SPV does not detect mapped device pointers which are being passed to kernel indirectly. The following test case return `0` instead of he correct value `123`.

```
#include <hip/hip_runtime_api.h>
#include <cstdio>
#include <cstdlib>

#define HIP_CHECK(X)                                                           \
  do {                                                                         \
    if (X != hipSuccess)                                                       \
      exit(2);                                                                 \
  } while (0)

struct Foo {
  int Bar;
  int *Data;
};

__global__ void kernel(Foo Out, const Foo In) { *Out.Data = *In.Data + In.Bar; }

int main() {
  hipDeviceProp_t Prop;
  int Device;
  HIP_CHECK(hipGetDevice(&Device));
  HIP_CHECK(hipGetDeviceProperties(&Prop, Device));
  if (!Prop.canMapHostMemory) {
    printf("Test requires canMapHostMemory == 1\n");
    exit(2);
  }

  int *InH, *OutH;
  HIP_CHECK(hipHostMalloc((void **)&InH, sizeof(int), hipHostMallocMapped));
  HIP_CHECK(hipHostMalloc((void **)&OutH, sizeof(int), hipHostMallocMapped));
  *InH = 23;
  *OutH = 0;

  int *InD, *OutD;
  HIP_CHECK(hipHostGetDevicePointer((void**)&InD, InH, 0));
  HIP_CHECK(hipHostGetDevicePointer((void**)&OutD, OutH, 0));

  Foo In = {100, InD}, Out = {0, OutD};

  kernel<<<dim3(1), dim3(1)>>>(Out, In);
  HIP_CHECK(hipDeviceSynchronize());

  printf("*OutH = %d\n", *OutH);
  bool Failed = *OutH != 123;

  HIP_CHECK(hipHostFree(InH));
  HIP_CHECK(hipHostFree(OutH));
  return Failed;
}
```

**Comment by pvelesko** [comment]
Does this still fail after first touch workaround?

**Comment by pjaaskel** [comment]
Does fixing this boil down to implementing hipHostRegister() so it registers the pointer down to SVM and also ensuring the pointer is registered when calling hipHostGetDevicePointer()?  Is your test program legal as it doesn't call hipHostRegister() first?
